baseURL = "http://kinnerapriyap.com/"
languageCode = "en-us"
isMultilingual = true
defaultContentLanguage = "en"
title = "Kinnera Priya Putti"
theme = "sam"
googleAnalytics = "UA-90329527-3"  

[params]
    description          = "Personal site of Kinnera Priya Putti"
    images               = ["me.jpg"]
    title                = "Kinnera Priya Putti"
    homepage = "home"
    footerText = "కిన్నెర | किन्नेरा | キンネラ"

[[params.mainMenu]]
    link = "work"
    text = "work"

[[params.mainMenu]]
    link = "about"
    text = "who is kinnera?"

[[params.mainMenu]]
    link = "https://twitter.com/kinnerapriyap"
    text = "ping me"