baseURL = "http://kinnerapriyap.com/"
languageCode = "en-us"
title = "Kinnera Priya Putti"
theme = "sam"
googleAnalytics = "UA-90329527-3"  

[params]
    homepage = "home"
    footerText = "కిన్నెర | किन्नेरा | キンネラ"

[[params.mainMenu]]
    link = "tech"
    text = "tech"

[[params.mainMenu]]
    link = "about"
    text = "who is kinnera?"

[[params.mainMenu]]
    link = "https://twitter.com/kinnerapriyap"
    text = "ping me"